@startuml

hide empty attributes
hide empty methods

class CollectionFactory {
    +get_collection(short_name)
}

class Collection {
    +short_name: unicode
    +name: unicode
}

class Resource {
    +name: unicode
    +urn: unicode
    +collection: Collection
    +local_pattern: unicode
    +timeslot: datetime
    +timeslot_string: unicode
    +dekade: int
    +year_day: int
    -name
    -urn
    -local_pattern
    -get_locations
    -post_locations
    +add_get_location()
    +add_post_location()
    +show_get_parameters()
    +show_post_parameters()
    +get_representation()
    +post_representation()
    +find_local()
    -show_mover_method_parameters()
}

@enduml
